[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"
  timeout = 30000
[build.environment]
  HUGO_VERSION = "0.55.6"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
